version: "3"

services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            active: true
            host: prisma-db
            port: 5432
            user: root
            password: prisma
  app:
    build: .
    ports: 
      - 4000:4000
    command: yarn dev
    links:
      - pg
    depends_on:
      - db
  pg:
    image: postgres:11
    restart: "always"
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=prisma
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - "./db/data:/var/lib/postgresql/data" 
      - "./db/init:/docker-entrypoint-initdb.d" 