version: "3"

services:
  app:
    build: . 
    restart: always
    container_name: heat
    environment:
      GITHUB_CLIENT_SECRET: cbe60362c1822b8ff5c591f2d0cf8ad4348be0ad
      GITHUB_CLIENT_ID: 8c765d55952df8c229e9
      PORT: 4000
      JWT: 42db3f171de92c64745ba942790a0e9f
    ports:
      - "4000:4000"
    volumes:
      - /usr/app